---
apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-ingress-configmap
data:
  traefik.toml: |
    defaultEntryPoints = ["https","http"]

    [entryPoints]

      [entryPoints.http]
      address = ":80"

      [entryPoints.https]
      address = ":443"
        [entryPoints.https.tls]
          [[entryPoints.https.tls.certificates]]
          CertFile = "/ssl/tls.crt"
          KeyFile = "/ssl/tls.key"

      [entryPoints.traefik]
        address = ":8080"
        [entryPoints.traefik.auth.basic]
        users = ["admin:$apr1$tUQT3hya$55t73RGXDWrzSwsClWTr3."]

    [kubernetes]
      [kubernetes.ingressEndpoint]
        publishedService = "traefik/traefik-ingress-controller-http-service"

    [ping]
    entryPoint = "http"

    [api]
    entryPoint = "traefik"
